### ISSUE TITLE
Bag types appear to be broken

### ISSUE THREAD

**Issue by Partonetrain** [SilentChaos512/Treasure-Bags#3]
### Versions

- **Treasure Bags**: 1.1.2+19
- **Forge**: 28.1.8
- **Modpack** (if applicable): Custom

### Expected behavior
Bags show correct color, and using them gives you the loot pool

### Actual behaviour
Bag displays "Unknown Type", even with valid type, such as treasurebag:spawn and does not work 

### Links/Images

![image](https://user-images.githubusercontent.com/19861808/65379605-502c6980-dc90-11e9-88c7-d69718de8215.png)

### Steps to reproduce the problem

1. Create a new world (also can use `/give @p treasurebags:treasure_bag{silentlib.LootContainer: {BagType: "<valid bag type>"}`})
2. Try to open, get nothing
3. View in inventory, "Unknown Type"

**Comment by SilentChaos512** [comment]
Could I get a log file, please? Last time I encountered an issue like this, it turned out to be another mod breaking the game. Considering this works fine in dev, I'm guessing that's the case here.

**Comment by Partonetrain** [comment]
My apologies, I had invalid JSON in a data pack. (No amount of disabling mods will help me there.) Sorry for wasting your time :(
